Addresses #27 adding support for maps the be serialized as json
wimdeblauwe/htmx-spring-boot-thymeleaf pull request #31
Opened 2022-10-26 22:49 UTC by checketts

2022-10-27 06:13 UTC, wimdeblauwe requested changes
Looks good in general, a few small remarks. Maybe also add a section to the readme that documents this?

Thanks for this!

2022-10-27 06:13 UTC, wimdeblauwe commented on src/main/java/io/github/wimdeblauwe/hsbt/thymeleaf/HtmxAttributeProcessor.java
>      public HtmxAttributeProcessor(final String dialectPrefix,
Maybe to be consistent, we can put each parameter on a new line. I would also remove the `final` of `dialectPrefix`, I find this is noise for little gain.

2022-10-27 06:13 UTC, wimdeblauwe commented on src/main/java/io/github/wimdeblauwe/hsbt/thymeleaf/HtmxAttributeProcessor.java
> +                    throw new TemplateProcessingException("Exception writing map", tag.getTemplateName() ,tag.getLine(), tag.getLine(), e);
```suggestion
                    throw new TemplateProcessingException("Exception writing map", tag.getTemplateName(), tag.getLine(), tag.getLine(), e);
```

2022-10-27 06:13 UTC, wimdeblauwe commented on src/test/java/io/github/wimdeblauwe/hsbt/thymeleaf/HtmxDialectTest.java
> +    void testWithHxVals() throws Exception {
Maybe also add a test with multiple values, maybe with a string, a boolean and a number to cover those 3 options?

2022-11-19 09:35 UTC, wimdeblauwe commented
@checketts Are you still working on this? I would like to release a 1.0.0 so I can also then release a 2.0.0 with Spring Boot 3 compatibility next week.

2022-11-27 16:32 UTC, wimdeblauwe approved these changes

2022-11-27 16:32 UTC, wimdeblauwe commented
@checketts Could you review the changes I have done to see if they are ok?

2022-11-27 16:44 UTC, merged

2022-11-28 04:59 UTC, checketts commented
I'm sorry an email rule was muting some github notifications to a subfolder and I just noticed it. Your changes look great, thanks for adding those test cases!